apiVersion: v1
kind: Pod
metadata:
  name: lab-05-almost-healthy
spec:
  containers:
  - name: api
    image: iacaksws1evgacr.azurecr.io/apia:v1
    imagePullPolicy: IfNotPresent
    resources: {}
    livenessProbe:
      httpGet:
        path: /health/almost_healthy
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3    
