apiVersion: v1
kind: Pod
metadata:
  name: lab-05-ready
spec:
  containers:
  - name: api
    image: iacaksws1evgacr.azurecr.io/apia:v1
    imagePullPolicy: IfNotPresent
    resources: {}
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3    
    readinessProbe:
      httpGet:
        path: /readiness
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3    
      
