apiVersion: v1
kind: Service
metadata:
  name: apia-service-2
  labels:
    app: lab6-task3
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: lab6-task3
  type: ClusterIP
